steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/save_cache:${_VERSION}'
  - '--tag=gcr.io/$PROJECT_ID/save_cache:latest'
  - '.'

# Test the script
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    mkdir -p /cache/folder1 /cache/folder2/subfolder3
    touch /cache/folder1/file1.txt
    touch /cache/folder1/file2.txt
    touch /cache/folder2/ignore.txt
    touch /cache/folder2/subfolder3/file1.txt
  volumes:
  - name: 'cache'
    path: '/cache'

- name: 'gcr.io/$PROJECT_ID/save_cache'
  args:
  - '--out=/cache'
  - '--key=simple-key-$( checksum cloudbuild.yaml )'
  - '--path=/cache/folder1'
  - '--path=/cache/folder2/subfolder3'
  volumes:
  - name: 'cache'
    path: '/cache'

- name: 'gcr.io/$PROJECT_ID/save_cache'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    ls -al /cache
    test -f /cache/simple-key-$( checksum cloudbuild.yaml ).tgz || echo "`ls -al /cache`"
  volumes:
  - name: 'cache'
    path: '/cache'


substitutions:
  _VERSION: '1.0'

images: 
- 'gcr.io/$PROJECT_ID/save_cache:${_VERSION}'
- 'gcr.io/$PROJECT_ID/save_cache:latest'
