steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/deploy_to_gcs:${_VERSION}'
  - '--tag=gcr.io/$PROJECT_ID/deploy_to_gcs:latest'
  - '.'

substitutions:
  _VERSION: '1.0'

images: 
- 'gcr.io/$PROJECT_ID/deploy_to_gcs:${_VERSION}'
- 'gcr.io/$PROJECT_ID/deploy_to_gcs:latest'
